# Generated by Django 5.1.1 on 2024-10-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_remove_profile_card_no_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
