# Generated by Django 5.1.1 on 2024-10-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0008_banner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Category_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
