# Generated by Django 5.1.1 on 2024-10-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0009_image_category_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='category',
        ),
    ]
