# Generated by Django 5.1.1 on 2024-09-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='text',
        ),
    ]
