# Generated by Django 5.1.1 on 2024-09-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0004_alter_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='suggest',
            field=models.BooleanField(null=True),
        ),
    ]
