# Generated by Django 5.1.1 on 2024-10-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0010_remove_comment_helpful_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
