# Generated by Django 5.1.1 on 2024-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0011_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
