# Generated by Django 5.1.1 on 2024-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0013_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
        migrations.AlterField(
            model_name='comment',
            name='negative_points',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='positive_points',
            field=models.TextField(null=True),
        ),
    ]
